name: Github Actions
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: AWS authentication
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: github clone my repo
        uses: actions/checkout@v2

      - name: Terraform ready to go
        uses: hashicorp/setup-terraform@v1

      - name: init our project
        run: terraform init

      - name: run a plan
        run: terraform plan

      - name: apply the plan
        run: terraform apply -auto-approve